@extends('layouts.app')
@section('title', 'News')

@section('content')
<div class="tab">
	<a href="about.php">ABOUT US</a>
	<a href="news.php" class="hover">NEWS</a>
</div>
<div class="container">
	<h2 class="news-detail-title">MIAO WEI ATTENDED THE 2017 INDUSTRIAL INTERNET SUMMIT AND DELIVERED A SPEECH</h2>
	<div class="news-detail-content">
		MIAO WEI ATTENDED THE 2017 INDUSTRIAL<br>
		MIAO WEI ATTENDED THE 2017 INDUSTRIALMIAO WEI ATTENDED THE 2017 INDUSTRIAL<br>
		MIAO WEI ATTENDED THE 2017<br>
		<br>
		<br>
		MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL <br>
		<br>
		MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO MIAO WEI ATTENDED THE 2017 INDUSTRIAL  WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL <br>
		<br>
		MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL  ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL MIAO WEI ATTENDED THE 2017 INDUSTRIAL <br>
	</div>
	<div class="news-detail-page">
		<a href="/post/{$previousPostID}">Prev News</a>
		<a href="/post/{$nextPostId}">Next News</a>
	</div>
</div>
@stop